camera: Changes to fix QCameraDisplay compilation issues
When using VNDK(-lite) camera does not build anymore for Mido, while it does for Tissot with same common tree.

device/xiaomi/mido/camera/QCamera2/util/QCameraDisplay.h:33:10: fatal error: 'gui/DisplayEventReceiver.h' file not found